import React from "react";
import "@/public/assets/css/vendors/bootstrap.min.css";
import "@/public/assets/css/vendors/swiper-bundle.min.css";
import "@/public/assets/css/vendors/nice-select.css";
import "@/public/assets/css/vendors/magnific-popup.css";
import "@/public/assets/css/vendors/odometer.css";
import "@/public/assets/css/vendors/spacing.css";


import "@/public/assets/css/main.css";
import "@/public/assets/css/sticky-cards.css";

import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import WebsiteActiveGuard from "@/components/WebsiteActiveGuard";

const dmSans = DM_Sans({
    subsets: ["latin"],
    display: "swap",
    variable: "--at-ff-body",
});

export const metadata: Metadata = {
    title: "Orisa - Multi-purpose Next.js Template",
    description: "Generated by Orisa - Next.js Template",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const redirectToComingSoon = process.env.WEBSITE_ACTIVE === "true";

    return (
        <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
            <head>
                {redirectToComingSoon && (
                    <script
                        dangerouslySetInnerHTML={{
                            __html: `if(window.location.pathname!=="/coming-soon"){window.location.replace("/coming-soon");}`,
                        }}
                    />
                )}
                {/* Vendor bundle path; matches original HTML template */}
                {/* eslint-disable-next-line @next/next/no-css-tags */}
                <link
                    href="/assets/css/vendors/font-awesome-pro.css"
                    rel="stylesheet"
                />
                {/* Blocking theme init before paint; App Router has no pages/_document for beforeInteractive Script */}
                {/* eslint-disable-next-line @next/next/no-sync-scripts */}
                <script src="/scripts/theme-init.js" />
            </head>
            <body className={`${dmSans.variable}`}>
                <div className="px-blur-bottom"></div>
                <WebsiteActiveGuard redirectToComingSoon={redirectToComingSoon}>
                    {children}
                </WebsiteActiveGuard>
            </body>
        </html>
    );
}
